---
#Various packages.
- name: ensure packages are installed.
  apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

# Individual packages (i.e. with no ppa).
- name: ensure non-ppa deb packages are installed.
  apt:
    deb: "{{ item }}"
  with_items: "{{ no_ppa_packages }}"
  become: true

# Remove packages that should not be present.
- name: ensure packages are uninstalled.
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apt_removals }}"
  become: true
