---
#Various packages.
- name: Install packages.
  apt:
    name: '{{ apt_packages }}'
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags:
    - packages

# Individual packages (i.e. with no ppa).
- name: Install non-ppa deb packages.
  apt:
    deb: "{{ item }}"
  with_items: "{{ no_ppa_packages }}"
  become: true

# Remove packages that should not be present.
- name: Uninstall packages.
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apt_removals }}"
  become: true
