---
- name: Converge
  hosts: all
  vars:
    apt_packages:
      - lxappearance
      - vim
    ubuntu_release: focal
    ppas:
      - source: "deb https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu {{ ubuntu_release }} main"
        fingerprint: "D89C66D0E31FEA2874EBD20561922AB60068FCD6"
        keyserver: "{{ default_keyserver }}"
    locale: en_US.UTF-8
    timezone: Europe/Berlin

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

    - name: install dirmngr requirement for adding apt key
      apt:
        name: dirmngr
        state: present

  tasks:
    - name: "Include ansible-role-ubuntu-setup"
      include_role:
        name: "ansible-role-ubuntu-setup"
